# docker-compose.yml
version: "3"
services:
  node:
    build: .
    depends_on:
      - postgres
    ports:
      - ${PORT}:${PORT}
    volumes:
      - logs:/app/logs
    restart: always
    networks:
      - my-net

  postgres:
    build: ./database
    image: postgres:latest
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - db:/var/lib/postgresql/data
    restart: always
    networks:
      - my-net

networks:
  my-net:
    name: my-custom-network
    driver: bridge

volumes:
  db:
  logs: